Repository replikation/poreCov, pull requests merged in 2021-02, with the labels that each got.

#46 Dev read classification
  README.md
  bin/json_parser.sh
  configs/container.config
  configs/local.config
  configs/nodes.config
  nextflow.config
  poreCov.nf
  workflows/determine_lineage.nf
  workflows/determine_mutations.nf
  workflows/process/download_database_kraken2.nf
  workflows/process/filter_fastq_by_length.nf
  workflows/process/guppy.nf
  workflows/process/kraken2.nf
  workflows/process/krona.nf
  workflows/process/nextclade.nf
  workflows/read_classification.nf
Labels: enhancement

#48 Dev mutation to db
  README.md
  bin/json_parser.sh
  configs/container.config
  configs/local.config
  data/figures/workflow.png
  nextflow.config
  poreCov.nf
  workflows/create_json_entries.nf
  workflows/create_tree.nf
  workflows/determine_lineage.nf
  workflows/process/augur.nf
  workflows/process/download_database_kraken2.nf
  workflows/process/json_report.nf
  workflows/process/kraken2.nf
  workflows/process/mask_alignment.nf
  workflows/process/toytree.nf
  workflows/read_classification.nf
  workflows/toytree.nf
Labels: enhancement, prio: high

#51 Summary report
  bin/summary_report.py
  configs/container.config
  modules/align_to_reference.nf
  modules/plot_coverages.nf
  poreCov.nf
  workflows/artic_nanopore_nCov19.nf
  workflows/create_summary_report.nf
  workflows/process/krona.nf
  workflows/process/nextclade.nf
  workflows/process/summary_report.nf
Labels: enhancement, prio: high

#60 Update guppy.nf
  workflows/process/guppy.nf
Labels: bug, prio: high
