Repository replikation/poreCov, pull requests merged in 2021-06, with the labels that each got.

#119 Covarplot & Reference BAM output
  configs/container.config
  configs/local.config
  configs/nodes.config
  modules/unused_modules/bwa_samtools.nf
  modules/unused_modules/coverage_plot.nf
  workflows/artic_nanopore_nCov19.nf
  workflows/process/artic.nf
  workflows/process/covarplot.nf
Labels: enhancement

#122 Split fasta improvment
  bin/split_fasta.py
Labels: enhancement

#117 V1200 read length parameter & guppy update
  nextflow.config
  poreCov.nf
  workflows/process/filter_fastq_by_length.nf
  workflows/process/guppy.nf
Labels: enhancement

#126 Add del to json
  bin/json_parser.py
Labels: enhancement

#129 stub dryrun tests
  .github/workflows/DryRun.yml
  .github/workflows/nextflow-test.yml
  modules/align_to_reference.nf
  modules/plot_coverages.nf
  modules/split_fasta.nf
  nextflow.config
  poreCov.nf
  workflows/process/artic.nf
  workflows/process/collect_fastq.nf
  workflows/process/covarplot.nf
  workflows/process/download_database_kraken2.nf
  workflows/process/filter_fastq_by_length.nf
  workflows/process/guppy.nf
  workflows/process/json_report.nf
  workflows/process/kraken2.nf
  workflows/process/krona.nf
  workflows/process/nanoplot.nf
  workflows/process/nextclade.nf
  workflows/process/pangolin.nf
  workflows/process/president.nf
  workflows/process/pycoqc.nf
  workflows/process/quality_genome_filter.nf
  workflows/process/rki_report.nf
  workflows/process/seqrs.nf
  workflows/process/summary_report.nf
Labels: enhancement, prio: low

#133 change nextclades base OS
  configs/container.config
Labels: bug, prio: high

#135 Fix134
  .github/workflows/DryRun.yml
  poreCov.nf
  workflows/artic_nanopore_nCov19.nf
Labels: bug, prio: high
