Repository replikation/poreCov, pull requests merged in 2021-03, with the labels that each got.

#68 Report updates
  bin/summary_report.py
Labels: enhancement

#70 bugfix for row swap, safe column adding
  bin/summary_report.py
Labels: prio: high

#81 Local cloud
  configs/nodes.config
  workflows/process/guppy.nf
Labels: bug, enhancement

#91 Add raw data table output
  bin/summary_report.py
  configs/container.config
  workflows/process/summary_report.nf
Labels: enhancement
